// export const ACTIONS = {
//     CHANGE_LEVEL: 'CHANGE_LEVEL',
//     CHANGE_SCENE: 'CHANGE_SCENE',
  
//     ADD_RUNE: 'ADD_RUNE',
//     ADD_ITEM: 'ADD_ITEM',
//     ADD_MOVE: 'ADD_MOVE',
//     INCREASE_MOVE_DAMAGE: 'INCREASE_MOVE_DAMAGE',
  
//     USE_ITEM: 'USE_ITEM',
  
//     SET_SCENE: 'SET_SCENE',
  
//     HEAL_PAL_FULL: 'HEAL_PAL_FULL',
//     SET_HEALTH: 'SET_HEALTH',
//     SET_GOLD: 'SET_GOLD',
//     SET_LEVEL: 'SET_LEVEL',
//     SET_INVENTORY: 'SET_INVENTORY',
//     ATTACK: 'ATTACK',
//     UPDATE_GAMEDATA: 'UPDATE_GAMEDATA',
//     SHOW_ATTACK: 'SHOW_ATTACK',
//     CLOSE_POPUP: 'CLOSE_POPUP',
//     CLOSE_DIALOG: 'CLOSE_DIALOG',
  
//     CHANGE_DIALOG: 'CHANGE_DIALOG',
//     SHOW_COUNTERS: 'SHOW_COUNTERS',
  
//     SWAP_PALS: 'SWAP_PALS',
//     // Phases:
//     PAY_PHASE: 'PAY_PHASE',
//     DAMAGE_PHASE: 'DAMAGE_PHASE',
//     STATUS_PHASE: 'STATUS_PHASE',
//     CLEANUP_PHASE: 'CLEANUP_PHASE',
//     END_PHASE: 'END_PHASE',
//     ADD_MOVE_TO_STACK: 'ADD_MOVE_TO_STACK',
  
//     TOGGLE_DEBUG: 'TOGGLE_DEBUG',
  
//     RESET_DATA: 'RESET_DATA',
//   }