import { uniqueId } from "../utils/reducer-utils"

export const allAvailableRewards = [
  {
    type: "fire",
    name: "Flame Toss",
    num: 9,
    cost: 1,
    id: uniqueId(),
  },
  {
    type: "fire",
    name: "Fire Breath",
    num: 11,
    cost: 1,
    id: uniqueId(),
  },
  {
    type: "fire",
    name: "Broil",
    num: 18,
    cost: 2,
    id: uniqueId(),
  },
  {
    type: "water",
    name: "Water Missile",
    num: 9,
    cost: 1,
    id: uniqueId(),
  },
  {
    type: "water",
    name: "Aqua Blast",
    num: 17,
    cost: 2,
    id: uniqueId(),
  },
  {
    type: "water",
    name: "Dripping Wet",
    num: 5,
    cost: 0,
    id: uniqueId(),
  },
  {
    type: "grass",
    name: "Grass Blade",
    num: 8,
    cost: 1,
    id: uniqueId(),
  },
  {
    type: "grass",
    name: "Pellet Gun",
    num: 10,
    cost: 1,
    id: uniqueId(),
  },
  {
    type: "grass",
    name: "Swarm",
    num: 19,
    cost: 2,
    id: uniqueId(),
  },
  {
    type: "poison",
    name: "Poisonous Sting",
    num: 3,
    cost: 1,
    id: uniqueId(),
    //high chance of poisoning
  },
  {
    type: "poison",
    name: "Shadow Drop",
    num: 6,
    cost: 1,
    id: uniqueId(),
    //K0 chance
  },
  {
    type: "poison",
    name: "Goo Punch",
    num: 10,
    cost: 1,
    id: uniqueId(),
    //Poison chance
  },
  { type: "poison", name: "syphon life", num: 4, cost: 2, id: uniqueId() },
  {
    type: "electric",
    name: "Electric Symphony",
    num: 8,
    cost: 1,
    id: uniqueId(),
  },
  {
    type: "normal",
    name: "backstab",
    num: 4,
    cost: 1,
    id: uniqueId(),
  },
  {
    type: "Ice",
    name: "Freeze Blast",
    num: 6,
    cost: 1,
    id: uniqueId(),
  },
  {
    type: "mind",
    name: "hypnotic distress",
    num: 5,
    cost: 1,
    id: uniqueId(),
  },
  {
    type: "pioson",
    name: "Black Ooze",
    num: 9,
    cost: 1,
    id: uniqueId(),
  },
  {
    type: "electric",
    name: "overload",
    num: 11,
    cost: 1,
    id: uniqueId(),
  },
]
