// import { uniqueId } from "../utils/reducer-utils"
import { EFFECTS } from "../effects"
const { POISON, STUN, SLEEP, DOUBLEDAMAGE, DRAW, BUILDUP, LIFESTEAL } = EFFECTS

export const poisonCards = {
  ToxicGas: {
    type: "Poison",
    name: "Toxic Gas",
    num: 0,
    cost: 2,
    // id: uniqueId(),
    effect: POISON,
    qty: 3,
    price: 37,
  },
  AcidSpray: {
    type: "Poison",
    name: "Acid Spray",
    num: 0,
    cost: 2,
    // id: uniqueId(),
    effect: POISON,
    qty: 6,
    price: 34,
  },
  ToxicSpores: {
    type: "Poison",
    name: "Toxic Spores",
    num: 0,
    cost: 2,
    // id: uniqueId(),
    effect: POISON,
    qty: 6,
  },
  PoisonousTouch: {
    type: "Poison",
    name: "Poisonous Touch",
    num: 0,
    cost: 1,
    // id: uniqueId(),
    effect: POISON,
    qty: 6,
  },
  ToxicOoze: {
    type: "Poison",
    name: "Toxic Ooze",
    num: 0,
    cost: 2,
    // id: uniqueId(),
    effect: POISON,
    qty: 6,
  },
  PoisonCloud: {
    type: "Poison",
    name: "Poison Cloud",
    num: 0,
    cost: 2,
    // id: uniqueId(),
    effect: POISON,
    qty: 6,
  },
}
export const stunCards = {
  throwFist: {
    type: "Electric",
    name: "Throw Fist",
    num: 3,
    cost: 2,
    //   id: uniqueId(),
    effect: STUN,
  },

  throwFistPlus: {
    type: "Electric",
    name: "Throw Fist+",
    num: 5,
    cost: 2,
    //   id: uniqueId(),
    effect: STUN,
  },
  chaoticBolt: {
    type: "Electric",
    name: "Chaotic Bolt",
    num: 3,
    cost: 2,
    //   id: uniqueId(),
    effectChance: 0.5,
    effect: STUN,
  },
}
export const ddamageCards = {
  focus: {
    type: "Physical",
    name: "Focus",
    num: 0,
    cost: 1,
    //   id: uniqueId(),
    effect: DOUBLEDAMAGE,
  },
  focusPunch: {
    type: "Physical",
    name: "Focus Punch",
    num: 2,
    cost: 1,
    //   id: uniqueId(),
    effect: DOUBLEDAMAGE,
  },
}
export const sleepCards = {
  hypnosis: {
    type: "Psychic",
    name: "Hypnosis",
    num: 0,
    cost: 2,
    //   id: uniqueId(),
    effect: SLEEP,
  },
  hypnosisPlus: {
    type: "Psychic",
    name: "Hypnosis+",
    num: 0,
    cost: 1,
    //   id: uniqueId(),
    effect: SLEEP,
  },
}
export const buildupCards = {
  channel: {
    type: "Psychic",
    name: "Channel",
    cost: 1,
    num: 1,
    qty: 0,
    effect: BUILDUP,
    // id: uniqueId(),
  },
  channelPlus: {
    type: "Psychic",
    name: "Channel Plus",
    cost: 1,
    num: 5,
    qty: 0,
    effect: BUILDUP,
    // id: uniqueId(),
  },
}
export const lifestealCards = {
  bloodsuck: {
    type: "Unholy",
    name: "Bloodsuck",
    cost: 1,
    num: 4,
    qty: 0,
    effect: LIFESTEAL,
    // id: uniqueId(),
  },
  drainingKiss: {
    type: "Unholy",
    name: "Draining Kiss",
    cost: 1,
    num: 6,
    qty: 0,
    effect: LIFESTEAL,
    // id: uniqueId(),
  },
}
export const rewardCards = {
  flameToss: {
    type: "fire",
    name: "Flame Toss",
    num: 9,
    cost: 1,
    // id: uniqueId(),
    effect: null,
  },
  fireBreath: {
    type: "fire",
    name: "Fire Breath",
    num: 11,
    cost: 1,
    // id: uniqueId(),
    effect: null,
  },
  broil: {
    type: "fire",
    name: "Broil",
    num: 18,
    cost: 2,
    // id: uniqueId(),
    effect: null,
  },
  waterMissile: {
    type: "water",
    name: "Water Missile",
    num: 9,
    cost: 1,
    // id: uniqueId(),
    effect: null,
  },
  aquaBlast: {
    type: "water",
    name: "Aqua Blast",
    num: 17,
    cost: 2,
    // id: uniqueId(),
    effect: null,
  },
  drippingWet: {
    type: "water",
    name: "Dripping Wet",
    num: 5,
    cost: 0,
    // id: uniqueId(),
    effect: null,
  },
  grassBlade: {
    type: "grass",
    name: "Grass Blade",
    num: 14,
    cost: 2,
    // id: uniqueId(),
    effect: null,
  },
  pelletGun: {
    type: "grass",
    name: "Pellet Gun",
    num: 10,
    cost: 1,
    // id: uniqueId(),
    effect: null,
  },
  swarm: {
    type: "grass",
    name: "Swarm",
    num: 19,
    cost: 2,
    // id: uniqueId(),
    effect: null,
  },
  shadowDrop: {
    type: "poison",
    name: "Shadow Drop",
    num: 6,
    cost: 0,
    // id: uniqueId(),
    effect: null,
    //K0 chance
  },
  electricSymphony: {
    type: "electric",
    name: "Electric Symphony",
    num: 13,
    cost: 2,
    // id: uniqueId(),
    effect: null,
  },
  backstab: {
    type: "normal",
    name: "backstab",
    num: 4,
    cost: 0,
    // id: uniqueId(),
    effect: null,
  },
  frostBlast: {
    type: "Ice",
    name: "Frost Blast",
    num: 9,
    cost: 1,
    // id: uniqueId(),
    effect: null,
  },
  hypnoticDistress: {
    type: "mind",
    name: "Hypnotic Distress",
    num: 8,
    cost: 1,
    // id: uniqueId(),
    effect: null,
  },
  blackOoze: {
    type: "pioson",
    name: "Black Ooze",
    num: 9,
    cost: 1,
    // id: uniqueId(),
    effect: null,
  },
  overload: {
    type: "electric",
    name: "overload",
    num: 11,
    cost: 1,
    // id: uniqueId(),
    effect: null,
  },
  stunningDelivery: {
    type: "electric",
    name: "Stunning Delivery",
    num: 7,
    cost: 1,
    // id: uniqueId(),
    effect: STUN,
  },
}
export const shopCards = {
  ToxicFog: {
    type: "Poison",
    name: "Toxic Fog",
    num: 0,
    cost: 3,
    effect: POISON,
    qty: 8,
    price: 39,
  },
  AcidRain: {
    type: "Poison",
    name: "Acid Rain",
    num: 0,
    cost: 3,
    effect: POISON,
    qty: 9,
    price: 37,
  },
  PoisonousMist: {
    type: "Poison",
    name: "Poisonous Mist",
    num: 0,
    cost: 2,
    effect: POISON,
    qty: 7,
    price: 36,
  },
  NoxiousBite: {
    type: "Poison",
    name: "Noxious Bite",
    num: 0,
    cost: 2,
    effect: POISON,
    qty: 6,
    price: 35,
  },
  VenomousFang: {
    type: "Poison",
    name: "Venomous Fang",
    num: 0,
    cost: 0,
    effect: POISON,
    qty: 4,
    price: 38,
  },
  PoisonousClaw: {
    type: "Poison",
    name: "Poisonous Claw",
    num: 0,
    cost: 2,
    effect: POISON,
    qty: 6,
    price: 36,
  },
  ElectroPunch: {
    type: "Electric",
    name: "Electro Punch",
    num: 11,
    cost: 2,
    effect: STUN,
    price: 37,
  },
  Shockwave: {
    type: "Electric",
    name: "Shockwave",
    num: 8,
    cost: 2,
    effect: STUN,
    price: 35,
  },
  ThunderFist: {
    type: "Electric",
    name: "Thunder Fist",
    num: 10,
    cost: 2,
    effect: STUN,
    price: 38,
  },
  PowerSurge: {
    type: "Electric",
    name: "Power Surge",
    num: 7,
    cost: 2,
    effect: STUN,
    price: 36,
  },
  ElectricBolt: {
    type: "Electric",
    name: "Electric Bolt",
    num: 14,
    cost: 3,
    effect: STUN,
    price: 37,
  },
  StrongHit: {
    type: "Physical",
    name: "Strong Hit",
    num: 5,
    cost: 2,
    effect: DOUBLEDAMAGE,
    price: 36,
  },
  PowerPunch: {
    type: "Physical",
    name: "Power Punch",
    num: 6,
    cost: 2,
    effect: DOUBLEDAMAGE,
    price: 38,
  },
  ForcefulBlow: {
    type: "Physical",
    name: "Forceful Blow",
    num: 5,
    cost: 2,
    effect: DOUBLEDAMAGE,
    price: 37,
  },
  DreamCatcher: {
    type: "Psychic",
    name: "Dream Catcher",
    num: 4,
    cost: 1,
    effect: SLEEP,
    price: 25,
  },
  HypnoWave: {
    type: "Psychic",
    name: "Hypno Wave",
    num: 3,
    cost: 1,
    effect: SLEEP,
    price: 22,
  },
  // Telekinesis: {
  //   type: "Psychic",
  //   name: "Telekinesis",
  //   num: 2,
  //   cost: 2,
  //   effect: LIFTING,
  //   price: 32,
  // },
  PsychicBlast: {
    type: "Psychic",
    name: "Psychic Blast",
    num: 1,
    cost: 2,
    effect: null,
    price: 29,
  },
}
export const basicCards = {
  flame: {
    type: "Fire",
    name: "Flame",
    num: 4,
    cost: 1,
    // id: uniqueId(),
    effect: null,
  },
  flamethrower: {
    type: "Fire",
    name: "Flamethrower",
    num: 8,
    cost: 1,
    // id: uniqueId(),
    effect: null,
  },
  gush: {
    type: "Water",
    name: "Gush",
    num: 2,
    cost: 1,
    // id: uniqueId(),
    effect: null,
  },
  gushPlus: {
    type: "Water",
    name: "Gush+",
    num: 6,
    cost: 1,
    // id: uniqueId(),
    effect: null,
  },
  think: {
    type: "Psychic",
    name: "Think",
    num: 0,
    cost: 0,
    // id: uniqueId(),
    effect: DRAW,
    qty: 1,
  },
  thinkPlus: {
    type: "Psychic",
    name: "Think+",
    num: 0,
    cost: 0,
    // id: uniqueId(),
    effect: DRAW,
    qty: 2,
  },
  recollectMind: {
    type: "Psychic",
    name: "Recollect Mind",
    num: 0,
    cost: 1,
    // id: uniqueId(),
    effect: DRAW,
    qty: 2,
  },
  recollectMindPlus: {
    type: "Psychic",
    name: "Recollect Mind+",
    num: 0,
    cost: 1,
    // id: uniqueId(),
    effect: DRAW,
    qty: 3,
  },
}
