import { uniqueId } from "../utils/reducer-utils"

export const allShopItems = [
  {
    type: "poison",
    name: "shop_syphon life",
    num: 4,
    cost: 2,
    id: uniqueId(),
    price: 12,
  },
  {
    type: "electric",
    name: "shop_electric symphonies",
    num: 8,
    cost: 1,
    id: uniqueId(),
    price: 40,
  },
  {
    type: "normal",
    name: "shop_backstab",
    num: 4,
    cost: 1,
    id: uniqueId(),
    price: 30,
  },
  {
    type: "ice",
    name: "shop_freeze blast",
    num: 6,
    cost: 1,
    id: uniqueId(),
    price: 60,
  },
  {
    type: "mind",
    name: "shop_hypnotic distress",
    num: 5,
    cost: 1,
    id: uniqueId(),
    price: 20,
  },
  {
    type: "pioson",
    name: "shop_black ooze",
    num: 9,
    cost: 1,
    id: uniqueId(),
    price: 35,
  },
  {
    type: "electric",
    name: "shop_overload",
    num: 11,
    cost: 1,
    id: uniqueId(),
    price: 55,
  },
]
