// import { SCENES } from "../scenes"
import { SCENES } from "../handlers/sceneHandlers_new"


//As for the areas, you could also add more like a tutorial level, a challenge level, a puzzle level, a secret level, etc.
const {
  // TRANSITION,
  INTRO,
  BATTLE,
  MAP,
  SHOP,
  REWARD,
  PACKREWARD,
  // CONVO,
  EVENT,
  REST,
  MINIBOSS,
  BOSS,
  GAMEOVER,
  VICTORY,
} = SCENES

export const mapGraphExample = [
  [["m"], ["m"], ["m"], ["m"], ["m"], ["m"]],
  [["x"], ["m"], ["x"], ["x"], ["m"], ["x"]],
  [["x"], ["x"], ["x"], ["m"], ["x"], ["x"]],
  [["x"], ["x"], ["x"], ["x"], ["e"], ["x"]],
  [["x"], ["x"], ["x"], ["x"], ["r"], ["x"]],
  [["x"], ["x"], ["x"], ["y"], ["x"], ["x"]],
  [["x"], ["x"], ["x"], ["x"], ["r"], ["x"]],
  [["x"], ["x"], ["x"], ["x"], ["x"], ["m"]],
  [["x"], ["x"], ["x"], ["x"], ["m"], ["x"]],
  [["x"], ["x"], ["x"], ["r"], ["x"], ["x"]],
  [["b"], ["b"], ["b"], ["b"], ["b"], ["b"]],
]

const mapGenerator = () => {
  return [
    GAMEOVER,
    INTRO,
    REWARD,
    // CONVO,
    MAP,
    BATTLE,
    PACKREWARD,
    REWARD,
    EVENT,
    MAP,
    SHOP,
    BATTLE,
    PACKREWARD,
    REWARD,
    MAP,
    EVENT,
    BATTLE,
    PACKREWARD,
    REWARD,
    MAP,
    REST,
    MINIBOSS,
    PACKREWARD,
    REWARD,
    MAP,
    BATTLE,
    PACKREWARD,
    REWARD,
    MAP,
    BATTLE,
    PACKREWARD,
    REWARD,
    REST,
    BOSS,
    VICTORY,
    // That is ACT1. If someone beats ACT1, we can start with ACT2 and ACT3
    // REWARD,
    // REWARD,
    // //Act 2
    // EVENT,
    // BATTLE,
    // REWARD,
    // SHOP,
    // BATTLE,
    // REWARD,
    // EVENT,
    // BATTLE,
    // REWARD,
    // REST,
    // MINIBOSS,
    // REWARD,
    // BATTLE,
    // REWARD,
    // BATTLE,
    // REWARD,
    // REST,
    // BOSS,
    // //Act 3
    // REWARD,
    // EVENT,
    // BATTLE,
    // REWARD,
    // SHOP,
    // BATTLE,
    // REWARD,
    // EVENT,
    // BATTLE,
    // REWARD,
    // REST,
    // MINIBOSS,
    // REWARD,
    // BATTLE,
    // REWARD,
    // BATTLE,
    // REWARD,
    // REST,
    // BOSS,
  ]
}

export const map = mapGenerator()
