export const enemyDefeatedResponses = [
  "You've bested me, brave warrior...",
  'I yield! Your strength is truly formidable.',
  'This is not the end... but a mere pause in my reign!',
  'I did not foresee such power in you...',
  'Defeated... by a mere mortal?',
  'You have won this time, but I will return stronger!',
  'Is this... the power of your conviction?',
  'I underestimated you... a costly mistake.',
  'My reign of terror... ended by you?',
  'I fall... but my legacy will live on.',
  'You have vanquished me... I commend your skill.',
  'So this is defeat... a bitter potion to swallow.',
  'I bow to your strength, for now...',
  'Inconceivable! Defeated by the likes of you!',
  'You may have won, but the war is far from over!',
  'Your victory is but a fleeting moment!',
  'So... the legends about you were true.',
  'I shall remember this defeat... and learn from it.',
  'You possess a strength I did not anticipate.',
  'This defeat... will only fuel my vengeance!',
  "You've turned the tide... for now.",
  'Impossible... My power... bested?',
  'Your victory will be short-lived, I assure you.',
  'You fight with honor... I respect that, even in defeat.',
  'I see now... your reputation is well-deserved.',
  "You've shattered my invincibility...",
  'Defeated, but not dishonored...',
  'You have bested me today... but tomorrow is another day.',
  'My defeat is but a stepping stone for your legend.',
  "Your strength... it's more than I imagined.",
  'I will rise again... stronger and wiser!',
  'A setback... but not the end of my journey.',
  "You've won the battle, not the war!",
  'Your power... where does it come from?',
  'This defeat is but a temporary setback!',
  'I will return, and I will be ready for you.',
  'You have earned my respect... and my rivalry.',
  'A loss today, but I will not be deterred.',
  'You may have won, but the darkness will return.',
  'This defeat... it teaches more than a victory ever could.',
  'I acknowledge your strength... for now.',
  'You have humbled me, but I will rise again.',
  'A momentary lapse... I shall return stronger.',
  'Your victory is a testament to your courage...',
  'This defeat... only makes me hungrier for victory.',
  "You've won, but the shadows will always return.",
  "Your strength is admirable... I'll remember this.",
  'A temporary triumph... I will have my revenge.',
  "I've fallen... but from ashes, I shall rise.",
  'You have bested me, but the darkness never sleeps.',
]
