const palAcronyms = [
  'Pixelated Animal Legends',
  'Prism-powered Animal Luminaries',
  'Pocket-sized Adventure League',
  'Parallel Animal Leaders',
  'Psychedelic Animal Lore',
  'Plushie Animal Liaisons',
  'Pixel Art Animal Lovers',
  'Pioneers of Animal Lands',
  'Paladins of Animal Liberation',
  'Playful Animal Legion',
  'Prodigious Animal Location',
  'Particle Acceleration Laboratory',
  'Peaceful Animal Location Team',
  'Protectors of Animal Life',
  'Phenomenal Animal Lords',
  'Prehistoric Animal Legends',
  'Puzzle-solving Animal Luminaries',
  'Pixel-powered Artifact Locators',
  'Prism-bound Adventure Lovers',
  'Pocket-sized Artifact Legends',
  'Parallel Artifact Locators',
  'Psychedelic Artifact Mysteries',
  'Plushie Artifact Magicians',
  'Pixel Art Artifact Lovers',
  'Pioneers of Artifact Magic',
  'Paladins of Artifact Lore',
  'Playful Artifact Mysteries',
  'Prodigious Artifact Locators',
  'Particle Acceleration Legacy',
  'Peaceful Artifact Location Society',
  'Protectors of Artifact Lands',
  'Phenomenal Artifact Leaders',
  'Prehistoric Artifact Liaisons',
  'Puzzle-solving Augmented Legends',
  'Pixel-powered Augmented Life',
  'Prism-empowered Artifact Locators',
  'Pocket-sized Adventure Mysteries',
  'Parallel Animal Mythology',
  'Psychedelic Augmented Lovers',
  'Plushie Artifact Magicians',
  'Pixel Art Animal Legends',
  'Pioneers of Astral Magic',
  'Paladins of Ancient Mythology',
  'Playful Artifact Magi',
  'Prodigious Artifact Lore',
  'Particle Acceleration Laboratory',
]

export function getRandomPALAcronym() {
  const randomIndex = Math.floor(Math.random() * palAcronyms.length)
  return palAcronyms[randomIndex]
}
