const palAcronyms = [
  "Pixelated Artifact Locators",
  "Prism-powered Adventure League",
  "Pocket-sized Animal Luminaries",
  "Parallel Adventure Leaders",
  "Psychedelic Artifact Legends",
  "Plushie Animal Legion",
  "Pixel Art Adventure Lovers",
  "Pioneers of Animal Magic",
  "Paladins of Ancient Lore",
  "Playful Animal Liaison",
  "Prodigious Animal Partners",
  "Particle Acceleration Legacy",
  "Peaceful Artifact Location Team",
  "Protectors of Arcane Lands",
  "Phantasmal Animal Lords",
  "Prehistoric Adventure Mystics",
  "Puzzle-solving Animal Mentors",
  "Pixel-powered Artifact Locating",
  "Prism-bound Adventure Magicians",
  "Pocket-sized Animal Legends",
  "Parallel Artifact Locators",
  "Psychedelic Adventure Lovers",
  "Plushie Animal Mythos",
  "Pixel Art Adventure Masters",
  "Pioneers of Animal Mythology",
  "Paladins of Animal Liberation",
  "Playful Animal Legends",
  "Prodigious Animal Liaisons",
  "Particle Acceleration Laboratory",
  "Peaceful Artifact Location Experts",
  "Protectors of Alien Life",
  "Phenomenal Animal Leaders",
  "Prehistoric Adventure Legends",
  "Puzzle-solving Animal Magicians",
  "Pixel-powered Artifact Location",
  "Prism-empowered Adventure Luminaries",
  "Pocket-sized Animal Lovers",
  "Parallel Artifact Location Team",
  "Psychedelic Animal Mysteries",
  "Plushie Adventure Lords",
  "Pixel Art Artifact Lovers",
  "Pioneers of Animal Realms",
  "Paladins of Ancient Magic",
  "Playful Animal Luminaries",
  "Prodigious Animal Legends",
  "Particle Acceleration Laboratory",
  "Peaceful Artifact Location Society",
  "Protectors of Alternate Lands",
  "Phenomenal Animal Liberationists",
  "Prehistoric Animal Liaisons",
  "Puzzle-solving Adventure Mystics",
  "Pixel-powered Augmented Life",
  "Prism-bound Animal Leaders",
  "Pocket-sized Artifact Locators",
  "Parallel Animal Lovers",
  "Psychedelic Artifact Mysteries",
  "Plushie Adventure Magicians",
  "Pixel Art Artifact Legends",
  "Pioneers of Animal Realities",
  "Paladins of Ancient Mythos",
  "Playful Animal Magi",
  "Prodigious Animal Lore",
  "Particle Acceleration Laboratory",
  "Peaceful Artifact Location Team",
  "Protectors of Astronomical Life",
  "Phenomenal Animal Luminaries",
  "Prehistoric Artifact Liaisons",
  "Puzzle-solving Augmented Legends",
  "Pixel-powered Animal Lovers",
  "Prism-empowered Artifact Locators",
  "Pocket-sized Adventure Mysteries",
  "Parallel Animal Mythology",
  "Psychedelic Augmented Lovers",
  "Plushie Artifact Magicians",
  "Pixel Art Animal Legends",
  "Pioneers of Astral Magic",
  "Paladins of Ancient Mythology",
  "Playful Artifact Magi",
  "Prodigious Artifact Lore",
  "Particle Acceleration Laboratory",
  "Peaceful Adventure Location Team",
  "Protectors of Ancient Mysteries",
  "Phenomenal Augmented Lifeforms",
  "Prehistoric Artifact Legends",
  "Puzzle-solving Augmented Mythos",
  "Pixel-powered Animal League",
  "Prism-empowered Artifact Leaders",
  "Pocket-sized Augmented Luminaries",
  "Parallel Artifact Liaisons",
  "Psychedelic Animal Magicians",
  "Plushie Augmented Legends",
  "Pixel Art Augmented Life",
  "Pioneers of Astral Mythology",
  "Paladins of Ancient Magic",
  "Playful Artifact Mysteries",
  "Prodigious Augmented Lore",
  "Particle Acceleration Laboratory",
  "Peaceful Adventure Location Society",
  "Protectors of Ancient Realities",
  "Phenomenal Augmented Leaders",
  "Prehistoric Augmented Mythology",
  "Puzzle-solving Artifact League",
  "Pixel-powered Augmented Leaders",
  "Prism-empowered Augmented Luminaries",
  "Pocket-sized Artifact Liaison",
  "Parallel Augmented Magicians",
  "Psychedelic Adventure Mythos",
  "Plushie Augmented Magicians",
  "Pixel Art Augmented Legends",
  "Pioneers of Astral Realities",
  "Paladins of Ancient Mysteries",
  "Playful Augmented Magic",
  "Prodigious Artifact Masters",
  "Particle Acceleration Laboratory",
  "Peaceful Adventure Location Team",
  "Protectors of Ancient Realms",
  "Phenomenal Augmented Luminaries",
  "Prehistoric Augmented Mythos",
  "Puzzle-solving Augmented League",
  "Pixel-powered Augmented Lifeforms",
  "Prism-empowered Artifact Location",
  "Pocket-sized Adventure Mythology",
  "Parallel Artifact Masters",
  "Psychedelic Augmented Magicians",
  "Plushie Adventure Magic",
  "Pixel Art Augmented Lore",
  "Pioneers of Astral Legends",
  "Paladins of Ancient Realities",
  "Playful Augmented Leaders",
  "Prodigious Artifact Liaisons",
  "Particle Acceleration Laboratory",
  "Peaceful Adventure Location Society",
  "Protectors of Ancient Mysteries",
  "Phenomenal Augmented Life",
  "Prehistoric Artifact Masters",
  "Puzzle-solving Augmented Mythology",
  "Pixel-powered Augmented League",
  "Prism-empowered Augmented Leaders",
  "Pocket-sized Artifact Luminaries",
  "Parallel Augmented Liaisons",
  "Psychedelic Augmented Magi",
  "Plushie Adventure Mythos",
  "Pixel Art Augmented Luminaries",
  "Pioneers of Astral Magic",
  "Paladins of Ancient Mythology",
  "Playful Augmented Masters",
  "Prodigious Artifact Mythos",
  "Particle Acceleration Laboratory",
  "Peaceful Adventure Location Team",
  "Protectors of Ancient Realms",
  "Phenomenal Augmented Leaders",
  "Prehistoric Augmented Mysteries",
  "Puzzle-solving Artifact League",
  "Pixel-powered Augmented Legends",
  "Prism-empowered Augmented Life",
  "Pocket-sized Augmented Liaison",
  "Parallel Augmented Magicians",
  "Psychedelic Augmented Mythos",
  "Plushie Artifact Mysteries",
  "Pixel Art Augmented Magic",
  "Pioneers of Astral Mythos",
  "Paladins of Ancient Magic",
  "Playful Augmented Mysteries",
  "Prodigious Augmented Masters",
  "Particle Acceleration Laboratory",
  "Peaceful Adventure Location Society",
  "Protectors of Ancient Realities",
  "Phenomenal Augmented Luminaries",
  "Prehistoric Augmented Mythology",
  "Puzzle-solving Artifact Leaders",
  "Pixel-powered Augmented League",
  "Prism-empowered Augmented Luminaries",
  "Pocket-sized Artifact Liaison",
  "Parallel Augmented Mythology",
  "Psychedelic Augmented League",
  "Plushie Artifact Magi",
  "Pixel Art Augmented Mysteries",
  "Pioneers of Astral Realms",
  "Paladins of Ancient Mysteries",
  "Playful Augmented Magic",
  "Prodigious Augmented Mythology",
  "Particle Acceleration Laboratory",
  "Peaceful Adventure Location Team",
  "Protectors of Ancient Realms",
  "Phenomenal Augmented Leaders",
  "Prehistoric Augmented Realities",
  "Puzzle-solving Artifact Luminaries",
];

export function getRandomPALAcronym() {
  const randomIndex = Math.floor(Math.random() * palAcronyms.length);
  return palAcronyms[randomIndex];
}
