export const rewardDialogs = [
    "Victory! A reward from your defeated foe awaits - what will it be?",
    "With your opponent vanquished, a singular, mysterious reward is presented.",
    "Your triumph secures a special prize. Let's see what fortune has granted you.",
    "The fallen enemy yields a reward. Discover what you've earned!",
    "A reward emerges from the battle's conclusion. Unveil your prize!",
    "Your conquest brings forth an unexpected reward. Reveal what awaits!",
    "One reward, one choice. The spoils of victory are uniquely yours.",
    "The enemy's defeat gifts you a surprise reward. What could it be?",
    "A single prize for a worthy victor. Claim your hard-earned reward!",
    "Your victory yields a special reward. The moment of revelation is here.",
    "The fallen foe offers a unique reward. Unwrap your victory prize!",
    "Triumph grants you one special prize. What treasure will you gain?",
    "Your prowess in battle earns a mysterious reward. Uncover your prize!",
    "A singular reward awaits your choice. What has fate bestowed upon you?",
    "The spoils of victory: one prize, one choice. Embrace your reward!",
    "Defeating your opponent unlocks a random reward. Let's see what you get!",
    "Your opponent's defeat brings a surprise. Unearth your singular reward!",
    "A single, random reward is yours for the taking. What will it be?",
    "In victory, a unique prize is revealed. Claim your exclusive reward!",
    "One reward, chosen by fate. Discover the bounty of your battle.",
    "Your enemy's end yields a special prize. What awaits you?",
    "Victory! A lone reward is unveiled. What treasure will you uncover?",
    "Defeat the enemy and uncover your unique reward. What surprise awaits?",
    "A sole reward for a grand victory. What fortune has favored you?",
    "The fallen enemy's gift is singular and mysterious. Unveil your reward!",
    "Your victory brings a random prize. Discover your exclusive reward!",
    "One prize for your triumph. What has destiny chosen for you?",
    "A reward awaits, singular and unknown. Unravel the mystery of your prize!",
    "Claim your prize from the defeated foe. A single, special reward!",
    "The spoils of battle: one mysterious reward. What will it be?",
    "Your conquest yields a unique bounty. Reveal your singular reward!",
    "A singular treasure from a vanquished enemy. What have you gained?",
    "Your opponent's fall brings a surprise prize. Discover what it is!",
    "One reward for your victory. Uncover the secret of your prize!",
    "A unique prize for a unique victory. What will your reward be?",
    "With the enemy defeated, a special reward is revealed. Claim it!",
    "The battlefield clears, unveiling one prize. What's your reward?",
    "Your strength earns one mysterious reward. Reveal your victory prize!",
    "Defeating the enemy grants a singular, random reward. Unveil it!",
    "Your victory over the enemy opens up a singular, exciting reward.",
    "A sole reward emerges from the battle's end. What have you won?",
    "One random reward for your triumph. What surprise lies in store?",
    "The enemy's downfall brings a unique reward. Discover your gain!",
    "One reward, one victory. Unveil the spoils of your conquest!",
    "A single prize for your combat skills. What will you uncover?",
    "Claim the sole reward from your vanquished foe. What awaits?",
    "Victory! A unique reward is yours to claim. What will it be?",
    "Your opponent's defeat brings forth one special prize. Reveal it!",
    "A singular, mysterious reward for your victory. What have you earned?",
    "One special prize awaits after your triumphant battle. Claim your reward!"
  ]
  